# Generated by Django 5.1.1 on 2024-10-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='outfits/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armario.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace_compra', models.URLField()),
                ('tipo', models.CharField(choices=[('parte_arriba', 'Parte de arriba'), ('pantalones', 'Pantalones'), ('zapatos', 'Zapatos')], max_length=15)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='armario.outfit')),
            ],
        ),
    ]
