# Generated by Django 5.1.1 on 2024-10-23 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0002_alter_outfit_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='outfit',
        ),
        migrations.AddField(
            model_name='outfit',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='pantalones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits_pantalones', to='armario.prenda'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='parte_superior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits_parte_superior', to='armario.prenda'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='zapatos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfits_zapatos', to='armario.prenda'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='enlace_compra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(choices=[('parte_superior', 'Parte Superior'), ('pantalones', 'Pantalones'), ('zapatos', 'Zapatos')], max_length=20),
        ),
    ]
