# Generated by Django 5.1.1 on 2024-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0004_remove_outfit_creador_remove_outfit_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='foto',
            field=models.ImageField(null=True, upload_to='outfits/'),
        ),
    ]
