# Generated by Django 5.1.1 on 2024-12-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0008_perfilusuario_delete_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(choices=[('parte_arriba', 'Parte de arriba'), ('pantalones', 'Pantalones'), ('zapatos', 'Zapatos'), ('accesorios', 'Accesorios')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='armario.outfit')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('outfit', 'usuario')},
            },
        ),
    ]
